# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Devpipe < Formula
  desc "Fast, local pipeline runner for development workflows"
  homepage "https://github.com/drewkhoury/devpipe"
  version "0.0.7"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/drewkhoury/devpipe/releases/download/v0.0.7/devpipe_0.0.7_darwin_amd64.tar.gz"
      sha256 "04935ad879ef99a274ca6862494bf0f106a7fe48e96c763eb22176f2a69e2f4a"

      def install
        bin.install "devpipe"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/drewkhoury/devpipe/releases/download/v0.0.7/devpipe_0.0.7_darwin_arm64.tar.gz"
      sha256 "46a754ccecae386abe605da5f65c8d64a1c3236244fa3eaf6b3db2cb61d1edb3"

      def install
        bin.install "devpipe"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/drewkhoury/devpipe/releases/download/v0.0.7/devpipe_0.0.7_linux_amd64.tar.gz"
      sha256 "0241d1f3bcf5636fb00893e1f61a6174acb372280cf3a1dc2de9dc3c3c0f1e63"
      def install
        bin.install "devpipe"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/drewkhoury/devpipe/releases/download/v0.0.7/devpipe_0.0.7_linux_arm64.tar.gz"
      sha256 "4c629970726e610cef44b06609f7bb70a09d9354d7d2a1878d002d8e5b9db9dc"
      def install
        bin.install "devpipe"
      end
    end
  end

  test do
    system "#{bin}/devpipe", "help"
  end
end
