# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Devpipe < Formula
  desc "Fast, local pipeline runner for development workflows"
  homepage "https://github.com/drewkhoury/devpipe"
  version "0.0.5"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/drewkhoury/devpipe/releases/download/v0.0.5/devpipe_0.0.5_darwin_amd64.tar.gz"
      sha256 "52c6778f37f9a4ef1b4d581628d47a507df11d06b41fa00a537dfc30e1c17952"

      def install
        bin.install "devpipe"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/drewkhoury/devpipe/releases/download/v0.0.5/devpipe_0.0.5_darwin_arm64.tar.gz"
      sha256 "6192a76e1ef7dbbdc6ffd28397edf57bdcf243cd97d60dbf9e20930535952833"

      def install
        bin.install "devpipe"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/drewkhoury/devpipe/releases/download/v0.0.5/devpipe_0.0.5_linux_amd64.tar.gz"
      sha256 "a67bc2f7bc809e380aebae206561e315151a6659f4c9f869b5eebe6d2456c136"
      def install
        bin.install "devpipe"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/drewkhoury/devpipe/releases/download/v0.0.5/devpipe_0.0.5_linux_arm64.tar.gz"
      sha256 "d690d2bacaae5fb9d512fac1aa1a65e885d72ee6de738a841fe6bb7f8f546efc"
      def install
        bin.install "devpipe"
      end
    end
  end

  test do
    system "#{bin}/devpipe", "help"
  end
end
